# Generated by Django 5.0.6 on 2024-06-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile_pictures/default_profile_picture.png', null=True, upload_to='static/uploaded_profile_pictures/'),
        ),
    ]
