# Generated by Django 5.0.6 on 2024-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
