# Generated by Django 5.0.6 on 2024-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0002_screening_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningroom',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Capienza della sala'),
        ),
        migrations.AlterField(
            model_name='screeningroom',
            name='name',
            field=models.CharField(help_text='Nome della sala (es. "Sala 1", "Sala 2", ...)', max_length=50),
        ),
    ]
