# Generated by Django 5.0.6 on 2024-06-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_release_date'),
        ('screenings', '0003_alter_screeningroom_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(help_text='Titolo del film', on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='price',
            field=models.FloatField(default=None, help_text='Prezzo del biglietto in € (float)'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='room',
            field=models.ForeignKey(help_text='Sala del cinema', on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screenings.screeningroom'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(help_text='Giorno ed orario di inizio'),
        ),
    ]
