# Generated by Django 5.0.6 on 2024-06-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_release_date'),
        ('screenings', '0004_alter_screening_movie_alter_screening_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='price',
            field=models.FloatField(default=None, help_text='Prezzo in €'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screenings.screeningroom'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
