# Generated by Django 5.0.6 on 2024-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_cast_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(help_text='Lista degli attori principali ("nome1 cognome1, nome2 cognome2, ..." e NO numeri)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(help_text='Regista del film ("nome cognome" e NO mumeri)', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(help_text='Genere del film (es. "Azione, Fantascienza, Horror, ..." e NO numeri)', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='Data di uscita (gg/mm/aaaa)'),
        ),
    ]
