# Generated by Django 5.0.6 on 2024-06-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_cast_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='Data di uscita (aaaa-mm-gg)'),
        ),
    ]
