# Generated by Django 5.0.6 on 2024-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(help_text='Data di uscita (mm/gg/aaaa)'),
        ),
    ]
